[[redirects]]
from = "http://cv.arnaud.sh/*"
to = "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
force = true

[[redirects]]
from = "https://cv.arnaud.sh/*"
to = "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
force = true

[[redirects]]
from = "http://42-cpiscine-tests.arnaud.sh/*"
to = "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
force = true

[[redirects]]
from = "https://42-cpiscine-tests.arnaud.sh/*"
to = "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
force = true
